import { Providers } from "@/graphql-client/lib/apollo-client";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import type { Metadata } from "next";
import BootstrapClient from "@/src/components/BootstrapClient";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

import Footer from "@/src/app/ui/footer/footer";
import Header from "@/src/app/ui/header/header";



export const metadata: Metadata = {
  title: {
    template: "%s | Blog App",
    default: "Blog App",
  },
  description: "Generated by create next app",
  keywords: "React, TypeScript, Next.js",
  icons: ["@/public/next.svg"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  

  return (
    <html lang="en">
      <body className="">
        <UserProvider>
            <Providers>
              <Header />
              {children}
              <Footer />
            </Providers>
        </UserProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
